# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
  node: circleci/node@3.0.0

jobs:
  gitops-checkout:
    executor: node/default
    steps:
      - run:
          name: Configure to clone Private Repository on GitHub
          command: |
            touch ~/.netrc
            chmod 0600 ~/.netrc
            printf "machine github.com\n  login ${GITHUB_ACCOUNT}\n  password ${GITHUB_PERSONAL_ACCESS_TOKEN}" > ~/.netrc

      - run:
          name: Checkout code (using shallow clone)
          command: |
            # Workaround old docker images with incorrect $HOME
            # check https://github.com/docker/docker/issues/2968 for details
            if [ "${HOME}" = "/" ]
            then
              export HOME=$(getent passwd $(id -un) | cut -d: -f6)
            fi
        
            git config --global gc.auto 0 || true
        
            # Checkout
            git clone --depth=1 --branch master --single-branch https://github.com/stephenharris/gitops-poc-env gitops
  
            # TODO Check the commit ID of the checked out code
      
      - run:
          name: Install kustomize
          command: |
            KUSTOMIZE_VERSION=3.8.7
            curl -L -o /usr/local/bin/kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v${KUSTOMIZE_VERSION}/kustomize_${KUSTOMIZE_VERSION}_linux_amd64
            chmod +x /usr/local/bin/kustomize
            kustomize version          
      
      - run:
          name: Change image in test environment
          command: |
            export APP_VERSION=$(cat version.txt)
            cd gitops/env/overlays/test/
            kustomize edit set image stephenharris13/stubapi=stephenharris13/stubapi:$APP_VERSION
            git status
            git diff
      
      
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
      - gitops-checkout
      
