# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
  node: circleci/node@3.0.0

jobs:
  gitops-checkout:
    executor: node/default
    steps:
      - run:
          name: Configure to clone Private Repository on GitHub
          command: |
            touch ~/.netrc
            chmod 0600 ~/.netrc
            printf "machine github.com\n  login ${GITHUB_ACCOUNT}\n  password ${GITHUB_PERSONAL_ACCESS_TOKEN}" > ~/.netrc
            cat ~/.netrc

      - run:
          name: Checkout code (using shallow clone)
          command: |
            # Workaround old docker images with incorrect $HOME
            # check https://github.com/docker/docker/issues/2968 for details
            if [ "${HOME}" = "/" ]
            then
              export HOME=$(getent passwd $(id -un) | cut -d: -f6)
            fi
        
            git config --global gc.auto 0 || true
        
            # Checkout
            git clone --depth=1 --branch master --single-branch github.com/stephenharris/gitops-poc-env gitops
  
            ls gitops
        
            # Check the commit ID of the checked out code
          
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
      - gitops-checkout
      
