name: Create pull request on env repo
on:
  push:
    branches:
    - "master"
    tags:
    - "*"
  
jobs:
  createPullRequest:
    name: Create PR
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install kustomize
      run: |
        opsys=linux  # or darwin, or windows
        curl -s https://api.github.com/repos/kubernetes-sigs/kustomize/releases |\
          grep browser_download |\
          grep $opsys |\
          cut -d '"' -f 4 |\
          grep /kustomize/v$version |\
          sort | tail -n 1 |\
          xargs curl -s -O -L

          if [ -e ./kustomize_v*_${opsys}_amd64.tar.gz ]; then
            tar xzf ./kustomize_v*_${opsys}_amd64.tar.gz
          else
            echo "Error: kustomize binary with the version $version does not exist!"
            exit 1
          fi
        ./kustomize version
        chmod u+x kustomize
        kustomize version

    - uses: actions/checkout@v2
      with:
        repository: stephenharris/gitops-poc-env
        ref: master
        path: env
        token: ${{ secrets.PAT }}

    - name: Create app version
      run: echo "::set-env name=APP_VER::1.3.6"

    - name: Change image in test environment
      run: |
        export APP_VERSION=$(cat version.txt)
        cd env/overlays/test/
        kustomize edit set image stephenharris13/stubapi=stephenharris13/stubapi:$APP_VERSION
        echo "::set-env name=APP_VERSION::$APP_VERSION"
          
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        path: env
        token: ${{ secrets.PAT }}
        commit-message: Update app
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: "app-${{env.APP_VERSION}}-${{env.COMMIT_SHA}}-${{ github.sha }}"
        delete-branch: true
        title: "[test] Updating app to ${{env.APP_VERSION}} / ${{ github.sha }}"
        body: |
          Update app to version ${{env.APP_VERSION}} / ${{ github.sha }}
        labels: |
          env:test
          app:app
        draft: false
